name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch: 

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: hs-dynamic

      - name: Run JFrog Scan
        run: |
          # 1. Pull the image
          jf docker pull hts2-hs-dock-demo-docker-local.jfrog.io/memcached:bookworm
          
          # 2. Scan the image. 
          # Note: We use the full tag. 
          # Adding --fail=false ensures the job finishes so you can see the summary 
          # even if vulnerabilities are found.
          jf docker scan hts2-hs-dock-demo-docker-local.jfrog.io/memcached:bookworm --fail=false
