name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch: 

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_URL }}/
        with:
          oidc-provider-name: hs-dynamic
          
      - name: Run JFrog Scan and Publish
        run: |
          # 1. Pull the image
          jf rt docker-pull hts2-hs-dock-demo-docker-local.jfrog.io/memcached:bookworm hts2-hs-dock-demo-docker-local --build-name="docker-ci" --build-number=${{ github.run_number }}

          
          # 2. Publish Build Info 
          jf rt build-publish "docker-ci" ${{ github.run_number }}

          # 3. Scan the Build 
          jf build-scan "docker-ci" ${{ github.run_number }}
